import { Header } from "@/widgets";
import "../../styles/globals.css";
import "../../styles/reset.min.css";
import localFont from "next/font/local";
import { ReactQueryProvider } from "@/ReactQueryProvider";
import { defaultLocale } from "../../middleware";
import { CSSProperties, Suspense } from "react";
import { Loader } from "@/shared";
import { PSuspense } from "@/PSuspense";

const myFont = localFont({
  src: "../../DIN Next W1G/dinnextw1g.otf",
  display: "swap",
});

export const metadata = {
  title: "Home | Byster",
  description: "Generated by create byster web site",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <ReactQueryProvider>
      <html lang={params.lang ?? defaultLocale}>
        <head>
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="favicon/apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="favicon/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="favicon/favicon-16x16.png"
          />
          <link rel="manifest" href="favicon/site.webmanifest" />
        </head>
        <body style={myFont.style}>
          <PSuspense>
            <Header lang={params.lang ?? defaultLocale} />
            {children}
          </PSuspense>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
