import { Header } from "@/widgets";
import "../styles/globals.css";
import "../styles/reset.min.css";
import localFont from "next/font/local";
import { ReactQueryProvider } from "@/ReactQueryProvider";

const myFont = localFont({
  src: "./DIN Next W1G/dinnextw1g.otf",
  display: "swap",
});

export const metadata = {
  title: "Home | Byster",
  description: "Generated by create byster web site",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="ru">
        <body style={myFont.style}>
          <Header />
          {children}
        </body>
      </html>
    </ReactQueryProvider>
  );
}
