import { Header } from "@/widgets";
import "../styles/globals.css";
import "../styles/reset.min.css";
import localFont from "next/font/local";
import { ReactQueryProvider } from "@/ReactQueryProvider";
import Head from "next/head";

const myFont = localFont({
  src: "./DIN Next W1G/dinnextw1g.otf",
  display: "swap",
});

export const metadata = {
  title: "Home | Byster",
  description: "Generated by create byster web site",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="ru">
        <Head>
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="favicon/apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="favicon/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="favicon/favicon-16x16.png"
          />
          <link rel="manifest" href="favicon/site.webmanifest" />
        </Head>
        <body style={myFont.style}>
          <Header />
          {children}
        </body>
      </html>
    </ReactQueryProvider>
  );
}
