import { Header } from "@/widgets";
import "../../styles/globals.css";
import "../../styles/reset.min.css";
import { Roboto } from "next/font/google";

import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { ReactQueryProvider } from "@/ReactQueryProvider";

const roboto = Roboto({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Home | Byster",
  description: "Generated by create byster web site",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "ru" }];
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  let messages: any;

  try {
    messages = (await import(`../../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <ReactQueryProvider>
      <html lang={locale}>
        <body style={roboto.style}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Header />
            {children}
          </NextIntlClientProvider>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
